#!/usr/bin/env python
#
# (c) 2013 Joost Yervante Damad <joost@damad.be>
# License: GPL

import sys

if __name__ == '__main__':
    if len(sys.argv) == 1:
      import main.madparts
      main.madparts.gui_main()
    else:
      import main.cli
      sys.exit(main.cli.cli_main())
