#!/opt/local/bin/python2.7
#
# (c) 2013 Joost Yervante Damad <joost@damad.be>
# License: GPL

import sys, string, os

if __name__ == '__main__':
    # if there is a file called 'Makefile' in the same directory
    # as this script, we're running from the development tree
    dirname = os.path.dirname(os.path.abspath(__file__))
    in_dev_tree = os.path.exists(os.path.join(dirname, 'Makefile'))
    if in_dev_tree:
      data_dir = dirname
    else:
      data_dir = os.path.join(sys.prefix, 'share', 'madparts')
      sys.path.append(data_dir)
    os.environ['DATA_DIR'] = data_dir

    if len(sys.argv) == 1:
      import main.madparts
      main.madparts.gui_main()
    else:
      import main.cli
      sys.exit(main.cli.cli_main())
