#!/usr/bin/env python
#
# (c) 2013 Joost Yervante Damad <joost@damad.be>
# License: GPL

import sys, string, os

if __name__ == '__main__':
    # trick needed to make OpenGL work on win32
    from ctypes import util
    try:
      from OpenGL.platform import win32
    except AttributeError:
      pass

    # if there is a file called 'Makefile' in the same directory
    # as this script, we're running from the development tree
    dirname = os.path.dirname(os.path.abspath(sys.argv[0]))
    in_dev_tree = os.path.exists(os.path.join(dirname, 'Makefile'))
    if in_dev_tree:
      print "in dev tree"
      data_dir = dirname
    else:
      data_dir = os.path.join(sys.prefix, 'share', 'madparts')
      sys.path.append(data_dir)
    os.environ['DATA_DIR'] = data_dir

    if len(sys.argv) == 1:
      import main.madparts
      sys.exit(main.madparts.gui_main())
    else:
      import main.cli
      sys.exit(main.cli.cli_main())
